Testing system. Written by Ivan Filimonau: by.epam.project.dao.DaoPerson.showResults
addPerson
checkLogin
deletePerson
editPerson
log
showPerson
showPerson
showPersons
showResults
SQL_ADD_PERSON
SQL_DELETE_PERSON_BY_ID
SQL_EDIT_PERSON
SQL_SELECT_USER_BY_LOGIN_AND_PASSWORD
SQL_SHOW_PERSON_BY_ID
SQL_SHOW_PERSONS
SQL_SHOW_RESULTS_BY_PERSON_ID
List<List<String> > by.epam.project.dao.DaoPerson.showResults (int personId)
Definition at line 99 of file DaoPerson.java.
References by.epam.project.dao.Dao.closeStatement(), by.epam.project.pool.ConnectionPool.getConnection(), by.epam.project.pool.ConnectionPool.getSinglePool(), and by.epam.project.pool.ConnectionPool.returnConnection().
Referenced by by.epam.project.command.person.ShowResultsCommand.execute().
{
                 List<List<String>> resultsList = new ArrayList<>();
                 Connection cn = null;
                 PreparedStatement st = null;
                 try {
                         cn = ConnectionPool.getSinglePool().getConnection();
                         st = cn.prepareStatement(SQL_SHOW_RESULTS_BY_PERSON_ID);
                         st.setInt(1, personId);
                         ResultSet result = st.executeQuery();
                         // result.next();
                         // resultsList.add(result.getString(1));
                         // resultsList.add(result.getString(2));
                         while (result.next()) {
                                 List<String> list = new ArrayList<>();
                                 list.add(result.getString(1));
                                 list.add(result.getString(2));
                                 list.add(result.getString(3));
                                 list.add(result.getString(4));
                                 list.add(String.valueOf(result.getInt(5)));
                                 resultsList.add(list);
                         }
                 } catch (SQLException | TechnicalException e) {
                         log.error(e);
                 } finally {
                         Dao.closeStatement(st);
                         ConnectionPool.getSinglePool().returnConnection(cn);
                 }
                 return resultsList;
         }