Testing system. Written by Ivan Filimonau: by.epam.project.controller.Controller.processRequest
Controller
destroy
doGet
doPost
init
log
processRequest
serialVersionUID
void by.epam.project.controller.Controller.processRequest (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException private
Definition at line 63 of file Controller.java.
References by.epam.project.command.factory.ActionFactory.defineCommand(), by.epam.project.command.ActionCommand.execute(), by.epam.project.resource.MessageManager.getProperty(), and by.epam.project.resource.ConfigurationManager.getProperty().
Referenced by by.epam.project.controller.Controller.doGet(), and by.epam.project.controller.Controller.doPost().
{
                 // substitution, unless create filters
                 // request.setCharacterEncoding("UTF-8");
                 String page = null;
                 // Define the command received from JSP
                 ActionFactory client = new ActionFactory();
                 ActionCommand command = client.defineCommand(request);
                 /*
                  *
                  * Call embodied method execute() and send parameters to the
                  * class-handler of concrete command
                  */
                 page = command.execute(request);
                 // this method return the page due to the sent command
                 if (page != null) {
                         RequestDispatcher dispatcher = getServletContext()
                                         .getRequestDispatcher(page);
                         // Call the page of the answer, according to the request
                         dispatcher.forward(request, response);
                 } else {
                         // Call the index page and set the attribute - "doesn't exist page"
                         page = ConfigurationManager.getProperty("path.page.index");
                         request.getSession().setAttribute("nullPage",
                                         MessageManager.getProperty("message.nullpage"));
                         response.sendRedirect(request.getContextPath() + page);
                 }
         }