Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.DeleteAnswerCommand.execute
execute
log
PARAM_NAME_ID
PARAM_NAME_QUESTION_ID
PARAM_TEST_ID
String by.epam.project.command.test.DeleteAnswerCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 20 of file DeleteAnswerCommand.java.
References by.epam.project.dao.DaoTest.deleteAnswer(), by.epam.project.resource.ConfigurationManager.getProperty(), and by.epam.project.dao.DaoTest.showQuestion().
{
                 log.debug("in attribute question lies = "
                                 + request.getAttribute("question"));
                 String page = null;
                 int testId = Integer.parseInt(request.getParameter(PARAM_TEST_ID));
                 int answerId = Integer.parseInt(request.getParameter(PARAM_NAME_ID));
                 int questionId = Integer.parseInt(request
                                 .getParameter(PARAM_NAME_QUESTION_ID));
                 DaoTest dao = new DaoTest();
                 boolean result = dao.deleteAnswer(answerId);
                 if (result) {
                         page = ConfigurationManager.getProperty("path.page.edit_question");
                         request.setAttribute("successfullyPerformedAction", "1");
                         request.setAttribute("testId", testId);
                         try {
                                 request.setAttribute("question", dao.showQuestion(questionId));
                         } catch (TechnicalException e) {
                                 log.error(e);
                         }
                 } else {
                         page = ConfigurationManager.getProperty("path.page.login");
                         request.setAttribute("successfullyPerformedAction", "0");
                 }
                 return page;
         }