Testing system (Written by Ivan Filimonau).: by.epam.project.logic.LoginLogic.checkLogin
checkLogin
getHash
log
int by.epam.project.logic.LoginLogic.checkLogin (String enterLogin, String enterPass)
Definition at line 13 of file LoginLogic.java.
References by.epam.project.dao.DaoPerson.checkLogin(), and by.epam.project.logic.LoginLogic.getHash().
Referenced by by.epam.project.command.login.LoginCommand.execute().
{
                 DaoPerson dao = new DaoPerson();
                 String passwordHash = getHash(enterPass);
                 return dao.checkLogin(enterLogin, passwordHash);
         }