Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.DeleteQuestionCommand.execute
execute
log
PARAM_NAME_QUESTION_ID
PARAM_TEST_ID
String by.epam.project.command.test.DeleteQuestionCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 18 of file DeleteQuestionCommand.java.
References by.epam.project.dao.DaoTest.deleteQuestion(), by.epam.project.resource.ConfigurationManager.getProperty(), by.epam.project.dao.DaoTest.showQuestion(), and by.epam.project.dao.DaoTest.showTest().
{
                 String page = null;
                 int testId = Integer.parseInt(request.getParameter(PARAM_TEST_ID));
                 int questionId = Integer.parseInt(request
                                 .getParameter(PARAM_NAME_QUESTION_ID));
                 DaoTest dao = new DaoTest();
                 boolean result = dao.deleteQuestion(questionId);
                 if (result) {
                         page = ConfigurationManager.getProperty("path.page.edit_questions");
                         request.setAttribute("successfullyPerformedAction", "1");
                         request.setAttribute("testId", testId);
                         try {
                                 request.setAttribute("test", dao.showTest(testId));
                                 request.setAttribute("question", dao.showQuestion(questionId));
                         } catch (TechnicalException e) {
                                 log.error(e);
                         }
                 } else {
                         page = ConfigurationManager.getProperty("path.page.login");
                         request.setAttribute("successfullyPerformedAction", "0");
                 }
                 return page;
         }