Testing system (Written by Ivan Filimonau).: by.epam.project.dao.DaoPerson.checkLogin
addPerson
checkLogin
deletePerson
editPerson
log
showPerson
showPerson
showPersons
showResults
SQL_ADD_PERSON
SQL_DELETE_PERSON_BY_ID
SQL_EDIT_PERSON
SQL_SELECT_USER_BY_LOGIN_AND_PASSWORD
SQL_SHOW_PERSON_BY_ID
SQL_SHOW_PERSONS
SQL_SHOW_RESULTS_BY_PERSON_ID
int by.epam.project.dao.DaoPerson.checkLogin (String name, String password)
Definition at line 37 of file DaoPerson.java.
References by.epam.project.dao.Dao.closeStatement(), by.epam.project.pool.ConnectionPool.getConnection(), by.epam.project.pool.ConnectionPool.getSinglePool(), and by.epam.project.pool.ConnectionPool.returnConnection().
Referenced by by.epam.project.logic.LoginLogic.checkLogin().
{
                 Connection cn = null;
                 PreparedStatement st = null;
                 int roleType = 0;
                 try {
                         cn = ConnectionPool.getSinglePool().getConnection();
                         st = cn.prepareStatement(SQL_SELECT_USER_BY_LOGIN_AND_PASSWORD);
                         st.setString(1, name);
                         st.setString(2, password);
                         ResultSet resultSet = st.executeQuery();
                         resultSet.next();
                         resultSet.getString("login");
                         resultSet.getString("password");
                         roleType = resultSet.getInt("role_type");
                 } catch (SQLException | TechnicalException e) {
                         log.error("Technical Exception", e);
                         return 0;
                 } finally {
                         Dao.closeStatement(st);
                         ConnectionPool.getSinglePool().returnConnection(cn);
                 }
                 return roleType;
         }