Testing system (Written by Ivan Filimonau).: by.epam.project.dao.DaoTest.showTest
addAnswer
addQuestion
addResult
addTest
deleteAnswer
deleteQuestion
deleteResult
deleteTest
editAnswer
editQuestion
editTest
log
showQuestion
showResult
showTest
showTests
SQL_ADD_ANSWER
SQL_ADD_QUESTION
SQL_ADD_RESULT
SQL_ADD_TEST
SQL_DELETE_ANSWER_BY_ID
SQL_DELETE_QUESTION_BY_ID
SQL_DELETE_RESULT_BY_PERSONID_TESTID
SQL_DELETE_TEST_BY_ID
SQL_EDIT_ANSWER
SQL_EDIT_QUESTION
SQL_EDIT_TEST
SQL_SHOW_ANSWERS_BY_QUESTION_TYPE
SQL_SHOW_QUESTION_BY_ID
SQL_SHOW_QUESTIONS_BY_TEST_TYPE
SQL_SHOW_RESULTS_BY_PERSON
SQL_SHOW_TEST_BY_ID
SQL_SHOW_TESTS_ID
Test by.epam.project.dao.DaoTest.showTest (int id) throws TechnicalException
Definition at line 52 of file DaoTest.java.
References by.epam.project.dao.Dao.closeStatement(), by.epam.project.pool.ConnectionPool.getConnection(), by.epam.project.pool.ConnectionPool.getSinglePool(), by.epam.project.pool.ConnectionPool.returnConnection(), by.epam.project.entity.test.Answer.setAnswer(), by.epam.project.entity.test.Question.setAnswers(), by.epam.project.entity.test.Question.setContent(), by.epam.project.entity.test.Test.setDescription(), by.epam.project.entity.test.Answer.setId(), by.epam.project.entity.test.Test.setId(), by.epam.project.entity.test.Question.setId(), by.epam.project.entity.test.Test.setQuestions(), by.epam.project.entity.test.Answer.setQuestionType(), by.epam.project.entity.test.Question.setTestType(), by.epam.project.entity.test.Test.setTitle(), and by.epam.project.entity.test.Answer.setValue().
Referenced by by.epam.project.logic.TestLogic.calculateResult(), by.epam.project.command.test.AddQuestionCommand.execute(), by.epam.project.command.test.DeleteQuestionCommand.execute(), by.epam.project.command.test.EditQuestionsCommand.execute(), by.epam.project.command.test.EditTestCommand.execute(), by.epam.project.command.test.EditWriteTestCommand.execute(), by.epam.project.command.test.WriteResultCommand.execute(), by.epam.project.command.test.PerformTestCommand.execute(), by.epam.project.command.test.PerformWriteTestCommand.execute(), and by.epam.project.dao.DaoTest.showTests().
{
                 Connection cn = null;
                 PreparedStatement st = null;
                 PreparedStatement statementForQuestions = null;
                 PreparedStatement statementForAnswers = null;
                 Test test = null;
                 cn = ConnectionPool.getSinglePool().getConnection();
                 try {
                         st = cn.prepareStatement(SQL_SHOW_TEST_BY_ID);
                         st.setInt(1, id);
                         ResultSet result = st.executeQuery();
                         result.next();
                         // ---Extracting from table "question" all questions according to
                         // type of the test.
                         Set<Question> questionsSet = new HashSet<>();
                         statementForQuestions = cn
                                         .prepareStatement(SQL_SHOW_QUESTIONS_BY_TEST_TYPE);
                         statementForQuestions.setInt(1, id);
                         ResultSet resultQuestions = statementForQuestions.executeQuery();
                         while (resultQuestions.next()) {
                                 int typeOfQuestion = resultQuestions.getInt("id");
                                 // ---Extracting from table "answer" all answers according to
                                 // type of the question, and save them in object "answer".
                                 List<Answer> answersList = new ArrayList<>();
                                 statementForAnswers = cn
                                                 .prepareStatement(SQL_SHOW_ANSWERS_BY_QUESTION_TYPE);
                                 statementForAnswers.setInt(1, typeOfQuestion);
                                 ResultSet resultAnswers = statementForAnswers.executeQuery();
                                 while (resultAnswers.next()) {
                                         Answer answer = new Answer();
                                         answer.setId(resultAnswers.getInt("id"));
                                         answer.setQuestionType(resultAnswers
                                                         .getInt("question_type"));
                                         answer.setAnswer(resultAnswers.getString("answer"));
                                         answer.setValue(resultAnswers.getInt("value"));
                                         // Save already filled object "answer" in the List.
                                         answersList.add(answer);
                                 }
                                 // ---Extracting from table "question" all questions according
                                 // to type of the test, and save them in object "question"
                                 Question question = new Question();
                                 question.setId(resultQuestions.getInt("id"));
                                 question.setTestType(typeOfQuestion);
                                 question.setContent(resultQuestions.getString("content"));
                                 question.setAnswers(answersList);
                                 // Save already filled object "question" in the Set.
                                 questionsSet.add(question);
                         }
                         // --------------
                         test = new Test();
                         test.setId(result.getInt("id"));
                         test.setTitle(result.getString("title"));
                         test.setDescription(result.getString("description"));
                         test.setQuestions(questionsSet);
                 } catch (SQLException e) {
                         throw new TechnicalException(e);
                 } finally {
                         Dao.closeStatement(st);
                         Dao.closeStatement(statementForQuestions);
                         Dao.closeStatement(statementForAnswers);
                         ConnectionPool.getSinglePool().returnConnection(cn);
                 }
                 log.debug("DAO method 'showTest' performed and return = " + test);
                 return test;
         }