Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.AddQuestionCommand.execute
execute
log
PARAM_NAME_QUESTION_CONTENT
PARAM_NAME_TEST_ID
String by.epam.project.command.test.AddQuestionCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 18 of file AddQuestionCommand.java.
References by.epam.project.dao.DaoTest.addQuestion(), by.epam.project.resource.ConfigurationManager.getProperty(), and by.epam.project.dao.DaoTest.showTest().
{
                 String page = null;
                 int testId = Integer.parseInt(request.getParameter(PARAM_NAME_TEST_ID));
                 String questionContent = request.getParameter(
                                 PARAM_NAME_QUESTION_CONTENT).trim();
                 // Checking for empty fields
                 DaoTest dao = new DaoTest();
                 if (questionContent.length() * testId != 0) {
                         boolean result = dao.addQuestion(testId, questionContent);
                         if (result) {
                                 page = ConfigurationManager
                                                 .getProperty("path.page.edit_questions");
                                 request.setAttribute("successfullyPerformedAction", "1");
                                 try {
                                         request.setAttribute("test", dao.showTest(testId));
                                 } catch (TechnicalException e) {
                                         log.error(e);
                                 }
                         } else {
                                 page = ConfigurationManager.getProperty("path.page.main_tutor");
                                 request.setAttribute("successfullyPerformedAction", "0");
                         }
                 } else {
                         request.setAttribute("errorEmptyFieldMessage", "true");
                         try {
                                 request.setAttribute("test", dao.showTest(testId));
                         } catch (TechnicalException e) {
                                 log.error(e);
                         }
                         page = ConfigurationManager.getProperty("path.page.edit_questions");
                 }
                 return page;
         }