Testing system (Written by Ivan Filimonau).: by.epam.project.command.login.LoginCommand.execute
execute
log
PARAM_NAME_ID
PARAM_NAME_LOGIN
PARAM_NAME_PASSWORD
String by.epam.project.command.login.LoginCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 37 of file LoginCommand.java.
References by.epam.project.logic.LoginLogic.checkLogin(), by.epam.project.logic.LoginLogic.getHash(), by.epam.project.entity.Person.getId(), by.epam.project.resource.ConfigurationManager.getProperty(), by.epam.project.dao.DaoPerson.showPerson(), by.epam.project.dao.DaoTest.showResult(), and by.epam.project.dao.DaoTest.showTests().
{
                 String page = null;
                 // Extracting from the request login and password
                 String login = request.getParameter(PARAM_NAME_LOGIN);
                 String pass = request.getParameter(PARAM_NAME_PASSWORD);
                 String personId = null;
                 // check the login and the password
                 LoginLogic logic = new LoginLogic();
                 DaoPerson dao = new DaoPerson();
                 DaoTest daoTest = new DaoTest();
                 switch (logic.checkLogin(login, pass)) {
                 case 3:
                         page = ConfigurationManager.getProperty("path.page.main_student");
                         request.getSession().setAttribute("role", "student");
                         try {
                                 String passMd5 = logic.getHash(pass);
                                 personId = String.valueOf(dao.showPerson(login, passMd5)
                                                 .getId());
                                 request.getSession().setAttribute("personId", personId);
                         } catch (TechnicalException e1) {
                                 log.error("login command: ", e1);
                         }
                         // In order to place in the request - "testsList" attribute
                         // (ArrayList object)
                         List<Test> tests = null;
                         try {
                                 tests = daoTest.showTests();
                         } catch (TechnicalException e1) {
                                 log.error(e1);
                         }
                         request.setAttribute("testsList", tests);
                         /*
                          * Previous variant, called another command from the current
                          * command. Not appropriate, cause - ruins MVC pattern. **
                          * ShowTestsCommand showTestsCommand = new ShowTestsCommand();
                          * showTestsCommand.execute(request);
                          */
                         // In order to place in the request - "result" attribute (HashMap
                         // object)
                         Map<Integer, Integer> resultMap = null;
                         int persId = Integer.parseInt(personId);
                         try {
                                 resultMap = daoTest.showResult(persId);
                         } catch (TechnicalException e1) {
                                 log.error(e1);
                         }
                         request.setAttribute("resultMap", resultMap);
                         /*
                          * Previous variant, called another command from the current
                          * command. Not appropriate, cause - ruins MVC pattern. **
                          * ShowResultCommand showResult = new ShowResultCommand();
                          * showResult.execute(request);
                          */
                         break;
                 case 2:
                         page = ConfigurationManager.getProperty("path.page.main_tutor");
                         request.getSession().setAttribute("role", "tutor");
                         break;
                 case 1:
                         page = ConfigurationManager.getProperty("path.page.main_root");
                         request.getSession().setAttribute("role", "root");
                         break;
                 default:
                         /*
                          * adding to the request: adding the attribute with name "language"
                          * and value taken from request from second hidden parameter
                          * "language". Variable was defined by the form of choose language
                          * in login.jsp with area of visibility - session.
                          */
                         request.setAttribute("language", request.getParameter("language"));
                         request.setAttribute("errorLoginPassMessage", "true");
                         page = ConfigurationManager.getProperty("path.page.login");
                 }
                 try {
                         String passMd5 = logic.getHash(pass);
                         request.setAttribute("person", dao.showPerson(login, passMd5));
                         request.getSession().setAttribute("personId",
                                         String.valueOf(dao.showPerson(login, passMd5).getId()));
                 } catch (TechnicalException e) {
                         log.error(e);
                 }
                 return page;
         }