Testing system (Written by Ivan Filimonau).: by.epam.project.resource.ConfigurationManager.getProperty
ConfigurationManager
getProperty
resourceBundle
static String by.epam.project.resource.ConfigurationManager.getProperty (String key) static
Definition at line 17 of file ConfigurationManager.java.
Referenced by by.epam.project.command.login.EmptyCommand.execute(), by.epam.project.command.login.LogoutCommand.execute(), by.epam.project.command.login.RegistrationCommand.execute(), by.epam.project.command.test.DeleteTestCommand.execute(), by.epam.project.command.person.DeletePersonCommand.execute(), by.epam.project.command.test.AddQuestionCommand.execute(), by.epam.project.command.test.AddTestCommand.execute(), by.epam.project.command.person.EditPersonCommand.execute(), by.epam.project.command.test.DeleteQuestionCommand.execute(), by.epam.project.command.test.EditQuestionsCommand.execute(), by.epam.project.command.test.EditTestCommand.execute(), by.epam.project.command.person.ShowPersonsCommand.execute(), by.epam.project.command.test.EditWriteQuestionCommand.execute(), by.epam.project.command.test.EditWriteTestCommand.execute(), by.epam.project.command.person.ShowResultsCommand.execute(), by.epam.project.command.test.DeleteAnswerCommand.execute(), by.epam.project.command.test.WriteResultCommand.execute(), by.epam.project.command.test.EditWriteAnswerCommand.execute(), by.epam.project.command.test.ShowResultCommand.execute(), by.epam.project.command.test.AddAnswerCommand.execute(), by.epam.project.command.test.ShowQuestionCommand.execute(), by.epam.project.command.person.EditWritePersonCommand.execute(), by.epam.project.command.test.ShowTestsCommand.execute(), by.epam.project.command.person.AddPersonCommand.execute(), by.epam.project.command.test.PerformTestCommand.execute(), by.epam.project.command.test.PerformWriteTestCommand.execute(), by.epam.project.command.login.LoginCommand.execute(), by.epam.project.controller.Controller.init(), and by.epam.project.controller.Controller.processRequest().
{
                 return resourceBundle.getString(key);
         }