Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.WriteResultCommand.execute
execute
log
PARAM_NAME_ID
PARAM_TEST_ID
PARAM_TEST_MARK
String by.epam.project.command.test.WriteResultCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 20 of file WriteResultCommand.java.
References by.epam.project.resource.ConfigurationManager.getProperty(), by.epam.project.dao.DaoTest.showTest(), and by.epam.project.logic.TestLogic.writeResult().
{
                 String page = null;
                 int personId = Integer.parseInt(((String) request.getSession()
                                 .getAttribute(PARAM_NAME_ID)).trim());
                 int testId = Integer.parseInt(request.getParameter(PARAM_TEST_ID));
                 int testMark = Integer.parseInt(request.getParameter(PARAM_TEST_MARK));
                 DaoTest dao = new DaoTest();
                 TestLogic logic = new TestLogic();
                 boolean result = logic.writeResult(personId, testId, testMark);
                 if (result) {
                         page = ConfigurationManager.getProperty("path.page.show_result");
                         request.setAttribute("successfullyPerformedAction", "1");
                         request.setAttribute("testResultFinal", testMark);
                         try {
                                 request.setAttribute("test", dao.showTest(testId));
                         } catch (TechnicalException e) {
                                 log.error(e);
                         }
                 }
                 return page;
         }