Testing system (Written by Ivan Filimonau).: by.epam.project.dao.DaoTest.showQuestion
addAnswer
addQuestion
addResult
addTest
deleteAnswer
deleteQuestion
deleteResult
deleteTest
editAnswer
editQuestion
editTest
log
showQuestion
showResult
showTest
showTests
SQL_ADD_ANSWER
SQL_ADD_QUESTION
SQL_ADD_RESULT
SQL_ADD_TEST
SQL_DELETE_ANSWER_BY_ID
SQL_DELETE_QUESTION_BY_ID
SQL_DELETE_RESULT_BY_PERSONID_TESTID
SQL_DELETE_TEST_BY_ID
SQL_EDIT_ANSWER
SQL_EDIT_QUESTION
SQL_EDIT_TEST
SQL_SHOW_ANSWERS_BY_QUESTION_TYPE
SQL_SHOW_QUESTION_BY_ID
SQL_SHOW_QUESTIONS_BY_TEST_TYPE
SQL_SHOW_RESULTS_BY_PERSON
SQL_SHOW_TEST_BY_ID
SQL_SHOW_TESTS_ID
Question by.epam.project.dao.DaoTest.showQuestion (int id) throws TechnicalException
Definition at line 155 of file DaoTest.java.
References by.epam.project.dao.Dao.closeStatement(), by.epam.project.pool.ConnectionPool.getConnection(), by.epam.project.pool.ConnectionPool.getSinglePool(), by.epam.project.pool.ConnectionPool.returnConnection(), by.epam.project.entity.test.Answer.setAnswer(), by.epam.project.entity.test.Question.setAnswers(), by.epam.project.entity.test.Question.setContent(), by.epam.project.entity.test.Answer.setId(), by.epam.project.entity.test.Question.setId(), by.epam.project.entity.test.Answer.setQuestionType(), by.epam.project.entity.test.Question.setTestType(), and by.epam.project.entity.test.Answer.setValue().
Referenced by by.epam.project.command.test.DeleteQuestionCommand.execute(), by.epam.project.command.test.EditWriteQuestionCommand.execute(), by.epam.project.command.test.DeleteAnswerCommand.execute(), by.epam.project.command.test.EditWriteAnswerCommand.execute(), by.epam.project.command.test.AddAnswerCommand.execute(), by.epam.project.command.test.ShowQuestionCommand.execute(), by.epam.project.command.test.PerformTestCommand.execute(), and by.epam.project.command.test.PerformWriteTestCommand.execute().
{
                 Connection cn = null;
                 PreparedStatement st = null;
                 PreparedStatement statementForAnswers = null;
                 Question question = null;
                 try {
                         cn = ConnectionPool.getSinglePool().getConnection();
                         st = cn.prepareStatement(SQL_SHOW_QUESTION_BY_ID);
                         st.setInt(1, id);
                         ResultSet result = st.executeQuery();
                         result.next();
                         int typeOfQuestion = result.getInt("id");
                         List<Answer> answersList = new ArrayList<>();
                         statementForAnswers = cn
                                         .prepareStatement(SQL_SHOW_ANSWERS_BY_QUESTION_TYPE);
                         statementForAnswers.setInt(1, typeOfQuestion);
                         ResultSet resultAnswers = statementForAnswers.executeQuery();
                         while (resultAnswers.next()) {
                                 Answer answer = new Answer();
                                 answer.setId(resultAnswers.getInt("id"));
                                 answer.setQuestionType(resultAnswers.getInt("question_type"));
                                 answer.setAnswer(resultAnswers.getString("answer"));
                                 answer.setValue(resultAnswers.getInt("value"));
                                 // Save already filled object "answer" in the List.
                                 answersList.add(answer);
                         }
                         question = new Question();
                         question.setId(result.getInt("id"));
                         question.setTestType(typeOfQuestion);
                         question.setContent(result.getString("content"));
                         question.setAnswers(answersList);
                 } catch (SQLException e) {
                         throw new TechnicalException(e);
                 } finally {
                         Dao.closeStatement(st);
                         Dao.closeStatement(statementForAnswers);
                         ConnectionPool.getSinglePool().returnConnection(cn);
                 }
                 return question;
         }