Testing system (Written by Ivan Filimonau).: by.epam.project.logic.TestLogic.calculateResult
calculateResult
checkQuestion
log
writeResult
int by.epam.project.logic.TestLogic.calculateResult (int testResult, int testId)
Definition at line 55 of file TestLogic.java.
References by.epam.project.entity.test.Test.getQuestions(), and by.epam.project.dao.DaoTest.showTest().
Referenced by by.epam.project.command.test.PerformWriteTestCommand.execute().
{
                 int counter = 0;
                 int finalResult = 0;
                 DaoTest dao = new DaoTest();
                 try {
                         Test test = dao.showTest(testId);
                         Set<Question> questions = test.getQuestions();
                         for (Question question : questions) {
                                 List<Answer> answers = question.getAnswers();
                                 for (Answer answer : answers) {
                                         log.debug("From TestLogic.calculateResult: answers(real) from logic= "
                                                         + answer.getValue());
                                         counter += answer.getValue();
                                 }
                         }
                 } catch (TechnicalException e) {
                         log.error(e);
                 }
                 finalResult = (int) (((double) testResult / counter) * 10);
                 return finalResult;
         }