Testing system (Written by Ivan Filimonau).: by.epam.project.dao.Dao.closeStatement
addAnswer
addQuestion
addResult
addTest
deleteAnswer
deleteQuestion
deleteResult
deleteTest
editAnswer
editQuestion
editTest
log
showQuestion
showResult
showTest
showTests
SQL_ADD_ANSWER
SQL_ADD_QUESTION
SQL_ADD_RESULT
SQL_ADD_TEST
SQL_DELETE_ANSWER_BY_ID
SQL_DELETE_QUESTION_BY_ID
SQL_DELETE_RESULT_BY_PERSONID_TESTID
SQL_DELETE_TEST_BY_ID
SQL_EDIT_ANSWER
SQL_EDIT_QUESTION
SQL_EDIT_TEST
SQL_SHOW_ANSWERS_BY_QUESTION_TYPE
SQL_SHOW_QUESTION_BY_ID
SQL_SHOW_QUESTIONS_BY_TEST_TYPE
SQL_SHOW_RESULTS_BY_PERSON
SQL_SHOW_TEST_BY_ID
SQL_SHOW_TESTS_ID
static void by.epam.project.dao.Dao.closeStatement (Statement st) static inherited
Definition at line 11 of file Dao.java.
Referenced by by.epam.project.dao.DaoTest.addAnswer(), by.epam.project.dao.DaoPerson.addPerson(), by.epam.project.dao.DaoTest.addQuestion(), by.epam.project.dao.DaoTest.addResult(), by.epam.project.dao.DaoTest.addTest(), by.epam.project.dao.DaoPerson.checkLogin(), by.epam.project.dao.DaoTest.deleteAnswer(), by.epam.project.dao.DaoPerson.deletePerson(), by.epam.project.dao.DaoTest.deleteQuestion(), by.epam.project.dao.DaoTest.deleteResult(), by.epam.project.dao.DaoTest.deleteTest(), by.epam.project.dao.DaoTest.editAnswer(), by.epam.project.dao.DaoPerson.editPerson(), by.epam.project.dao.DaoTest.editQuestion(), by.epam.project.dao.DaoTest.editTest(), by.epam.project.dao.DaoPerson.showPerson(), by.epam.project.dao.DaoPerson.showPersons(), by.epam.project.dao.DaoTest.showQuestion(), by.epam.project.dao.DaoTest.showResult(), by.epam.project.dao.DaoPerson.showResults(), by.epam.project.dao.DaoTest.showTest(), and by.epam.project.dao.DaoTest.showTests().
{
                 if (st != null){
                         try {
                                 st.close();
                         } catch (SQLException e) {
                                 log.error("Technical Exception", e);
                         }
                 }
         }