Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.ShowTestsCommand.execute
execute
log
String by.epam.project.command.test.ShowTestsCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 24 of file ShowTestsCommand.java.
References by.epam.project.resource.ConfigurationManager.getProperty(), by.epam.project.dao.DaoPerson.showPerson(), by.epam.project.dao.DaoTest.showResult(), and by.epam.project.dao.DaoTest.showTests().
{
                 List<Test> tests = null;
                 Map<Integer, Integer> resultMap = null;
                 String page = null;
                 DaoTest dao = new DaoTest();
                 DaoPerson daoPerson = new DaoPerson();
                 try {
                         tests = dao.showTests();
                         log.debug("list of tests = " + tests);
                         request.setAttribute("testsList", tests);
                         request.setAttribute("successfullyPerformedAction",
                                         request.getParameter("successfullyPerformedAction"));
                         String role = (String) request.getSession().getAttribute("role");
                         int personId = Integer.parseInt((String) request.getSession()
                                         .getAttribute("personId"));
                         switch (role) {
                         case "student":
                                 /*
                                  * In order to place in the request - "result" and "person"
                                  * attribute (HashMap object and bean object)
                                  */
                                 resultMap = dao.showResult(personId);
                                 request.setAttribute("resultMap", resultMap);
                                 request.setAttribute("person", daoPerson.showPerson(personId));
                                 page = ConfigurationManager
                                                 .getProperty("path.page.main_student");
                                 break;
                         case "tutor":
                                 page = ConfigurationManager.getProperty("path.page.main_tutor");
                                 break;
                         case "root":
                                 page = ConfigurationManager.getProperty("path.page.main_tutor");
                                 break;
                         }
                 } catch (TechnicalException e) {
                         log.error(e);
                         page = ConfigurationManager.getProperty("path.page.login");
                 }
                 return page;
         }