Testing system (Written by Ivan Filimonau).: by.epam.project.dao.DaoTest.showTests
addAnswer
addQuestion
addResult
addTest
deleteAnswer
deleteQuestion
deleteResult
deleteTest
editAnswer
editQuestion
editTest
log
showQuestion
showResult
showTest
showTests
SQL_ADD_ANSWER
SQL_ADD_QUESTION
SQL_ADD_RESULT
SQL_ADD_TEST
SQL_DELETE_ANSWER_BY_ID
SQL_DELETE_QUESTION_BY_ID
SQL_DELETE_RESULT_BY_PERSONID_TESTID
SQL_DELETE_TEST_BY_ID
SQL_EDIT_ANSWER
SQL_EDIT_QUESTION
SQL_EDIT_TEST
SQL_SHOW_ANSWERS_BY_QUESTION_TYPE
SQL_SHOW_QUESTION_BY_ID
SQL_SHOW_QUESTIONS_BY_TEST_TYPE
SQL_SHOW_RESULTS_BY_PERSON
SQL_SHOW_TEST_BY_ID
SQL_SHOW_TESTS_ID
List<Test> by.epam.project.dao.DaoTest.showTests () throws TechnicalException
Definition at line 131 of file DaoTest.java.
References by.epam.project.dao.Dao.closeStatement(), by.epam.project.pool.ConnectionPool.getConnection(), by.epam.project.pool.ConnectionPool.getSinglePool(), by.epam.project.pool.ConnectionPool.returnConnection(), and by.epam.project.dao.DaoTest.showTest().
Referenced by by.epam.project.command.test.DeleteTestCommand.execute(), by.epam.project.command.test.AddTestCommand.execute(), by.epam.project.command.test.EditWriteTestCommand.execute(), by.epam.project.command.test.ShowTestsCommand.execute(), and by.epam.project.command.login.LoginCommand.execute().
{
                 List<Test> tests = new ArrayList<>();
                 Connection cn = null;
                 Statement st = null;
                 cn = ConnectionPool.getSinglePool().getConnection();
                 try {
                         st = cn.createStatement();
                         ResultSet result = st.executeQuery(SQL_SHOW_TESTS_ID);
                         while (result.next()) {
                                 Test test = showTest(result.getInt("id"));
                                 tests.add(test);
                         }
                 } catch (SQLException e) {
                         throw new TechnicalException(e);
                 } finally {
                         Dao.closeStatement(st);
                         ConnectionPool.getSinglePool().returnConnection(cn);
                 }
                 return tests;
         }