Testing system (Written by Ivan Filimonau).: by.epam.project.command.person.AddPersonCommand.execute
execute
log
PARAM_NAME_FIRST_NAME
PARAM_NAME_LOGIN
PARAM_NAME_PASSWORD
PARAM_NAME_ROLE
PARAM_NAME_SECOND_NAME
String by.epam.project.command.person.AddPersonCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 25 of file AddPersonCommand.java.
References by.epam.project.dao.DaoPerson.addPerson(), by.epam.project.logic.LoginLogic.getHash(), and by.epam.project.resource.ConfigurationManager.getProperty().
{
                 String page = null;
                 // Extracting parameters from the request
                 String login = request.getParameter(PARAM_NAME_LOGIN);
                 String pass = request.getParameter(PARAM_NAME_PASSWORD);
                 String firstName = request.getParameter(PARAM_NAME_FIRST_NAME);
                 String secondName = request.getParameter(PARAM_NAME_SECOND_NAME);
                 int role = Integer.parseInt(request.getParameter(PARAM_NAME_ROLE));
                 if (firstName.length() * secondName.length() * login.length()
                                 * pass.length() == 0) {
                         request.setAttribute("errorEmptyFieldMessage", "true");
                         page = ConfigurationManager.getProperty("path.page.registration");
                 } else {
                         DaoPerson dao = new DaoPerson();
                         LoginLogic logic = new LoginLogic();
                         pass = logic.getHash(pass);
                         boolean result = dao.addPerson(firstName, secondName, login, pass,
                                         role);
                         page = ConfigurationManager.getProperty("path.page.login");
                         if (!result) {
                                 request.setAttribute("errorDuplicateEntryMessage", "true");
                                 page = ConfigurationManager
                                                 .getProperty("path.page.registration");
                         }
                         // Return string with the address of the login page
                 }
                 return page;
         }