Testing system (Written by Ivan Filimonau).: by.epam.project.pool.ConnectionPool.getConnection
cleanUpPool
ConnectionPool
createPool
getConnection
getSinglePool
instance
lock
log
pool
POOL_SIZE
returnConnection
Connection by.epam.project.pool.ConnectionPool.getConnection () throws TechnicalException
Definition at line 60 of file ConnectionPool.java.
Referenced by by.epam.project.dao.DaoTest.addAnswer(), by.epam.project.dao.DaoPerson.addPerson(), by.epam.project.dao.DaoTest.addQuestion(), by.epam.project.dao.DaoTest.addResult(), by.epam.project.dao.DaoTest.addTest(), by.epam.project.dao.DaoPerson.checkLogin(), by.epam.project.dao.DaoTest.deleteAnswer(), by.epam.project.dao.DaoPerson.deletePerson(), by.epam.project.dao.DaoTest.deleteQuestion(), by.epam.project.dao.DaoTest.deleteResult(), by.epam.project.dao.DaoTest.deleteTest(), by.epam.project.dao.DaoTest.editAnswer(), by.epam.project.dao.DaoPerson.editPerson(), by.epam.project.dao.DaoTest.editQuestion(), by.epam.project.dao.DaoTest.editTest(), by.epam.project.junit.ConnectionPoolTest.GetConnectionTest(), by.epam.project.dao.DaoPerson.showPerson(), by.epam.project.dao.DaoPerson.showPersons(), by.epam.project.dao.DaoTest.showQuestion(), by.epam.project.dao.DaoTest.showResult(), by.epam.project.dao.DaoPerson.showResults(), by.epam.project.dao.DaoTest.showTest(), and by.epam.project.dao.DaoTest.showTests().
{
                 Connection connection = null;
                 try {
                         connection = pool.take();
                 } catch (InterruptedException e) {
                         throw new TechnicalException("check connection for null ", e);
                 }
                 log.debug("pool size = " + pool.size());
                 return connection;
         }