Testing system (Written by Ivan Filimonau).: by.epam.project.dao.DaoPerson.showPerson
addPerson
checkLogin
deletePerson
editPerson
log
showPerson
showPerson
showPersons
showResults
SQL_ADD_PERSON
SQL_DELETE_PERSON_BY_ID
SQL_EDIT_PERSON
SQL_SELECT_USER_BY_LOGIN_AND_PASSWORD
SQL_SHOW_PERSON_BY_ID
SQL_SHOW_PERSONS
SQL_SHOW_RESULTS_BY_PERSON_ID
Person by.epam.project.dao.DaoPerson.showPerson (int id) throws TechnicalException
Definition at line 134 of file DaoPerson.java.
References by.epam.project.dao.Dao.closeStatement(), by.epam.project.pool.ConnectionPool.getConnection(), by.epam.project.pool.ConnectionPool.getSinglePool(), by.epam.project.pool.ConnectionPool.returnConnection(), by.epam.project.entity.person.Person.setFirstName(), by.epam.project.entity.person.Person.setId(), by.epam.project.entity.person.Person.setLogin(), by.epam.project.entity.person.Person.setPassword(), by.epam.project.entity.person.Person.setRoleType(), and by.epam.project.entity.person.Person.setSecondName().
Referenced by by.epam.project.command.person.EditPersonCommand.execute(), by.epam.project.command.test.ShowTestsCommand.execute(), by.epam.project.command.test.PerformTestCommand.execute(), by.epam.project.command.test.PerformWriteTestCommand.execute(), and by.epam.project.command.login.LoginCommand.execute().
{
                 Connection cn = null;
                 PreparedStatement st = null;
                 Person person = new Person();
                 cn = ConnectionPool.getSinglePool().getConnection();
                 try {
                         st = cn.prepareStatement(SQL_SHOW_PERSON_BY_ID);
                         st.setInt(1, id);
                         ResultSet result = st.executeQuery();
                         result.next();
                         person.setId(result.getInt("id"));
                         person.setRoleType(result.getInt("role_type"));
                         person.setFirstName(result.getString("first_name"));
                         person.setSecondName(result.getString("second_name"));
                         person.setLogin(result.getString("login"));
                         person.setPassword(result.getString("password"));
                 } catch (SQLException e) {
                         throw new TechnicalException(e);
                 } finally {
                         Dao.closeStatement(st);
                         ConnectionPool.getSinglePool().returnConnection(cn);
                 }
                 return person;
         }