Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.EditWriteTestCommand.execute
execute
log
PARAM_NAME_DESCRIPTION
PARAM_NAME_ID
PARAM_NAME_TITLE
String by.epam.project.command.test.EditWriteTestCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 19 of file EditWriteTestCommand.java.
References by.epam.project.dao.DaoTest.editTest(), by.epam.project.resource.ConfigurationManager.getProperty(), by.epam.project.dao.DaoTest.showTest(), and by.epam.project.dao.DaoTest.showTests().
{
                 String page = null;
                 int id = Integer.parseInt(request.getParameter(PARAM_NAME_ID).trim());
                 String title = request.getParameter(PARAM_NAME_TITLE).trim();
                 String description = request.getParameter(PARAM_NAME_DESCRIPTION).trim();
                 // Checking for empty fields
                 DaoTest dao = new DaoTest();
                 if (title.length() * description.length() * id != 0) {
                         boolean result = dao.editTest(id, title, description);
                         if (result) {
                                 page = ConfigurationManager.getProperty("path.page.main_tutor");
                                 request.setAttribute("successfullyPerformedAction", "1");
                                 try {
                                         request.setAttribute("testsList", dao.showTests());
                                 } catch (TechnicalException e) {
                                         log.error(e);
                                 }
                         } else {
                                 page = ConfigurationManager.getProperty("path.page.main_tutor");
                                 request.setAttribute("successfullyPerformedAction", "0");
                         }
                 } else {
                         page = ConfigurationManager.getProperty("path.page.edit_test");
                         request.setAttribute("errorEmptyFieldMessage", "true");
                         try {
                                 request.setAttribute("test", dao.showTest(id));
                         } catch (TechnicalException e) {
                                 log.error(e);
                         }
                 }
                 return page;
         }