Testing system (Written by Ivan Filimonau).: by.epam.project.logic.LoginLogic.getHash
checkLogin
getHash
log
String by.epam.project.logic.LoginLogic.getHash (String str)
Definition at line 27 of file LoginLogic.java.
Referenced by by.epam.project.logic.LoginLogic.checkLogin(), by.epam.project.command.person.EditWritePersonCommand.execute(), by.epam.project.command.person.AddPersonCommand.execute(), and by.epam.project.command.login.LoginCommand.execute().
{
                 MessageDigest md5; // variable with reference to MessageDigest class.
                 StringBuffer hexString = new StringBuffer();
                 try {
                         // Gaining an object type MessageDigest
                         md5 = MessageDigest.getInstance("md5");
                         md5.reset();
                         // handling password(String) by MessageDigest object(md5).
                         // String.getBytes() - returns string with array of bytes.
                         md5.update(str.getBytes());
                         // perform md5 algorithm and return an array of bytes.
                         byte messageDigest[] = md5.digest();
                         // building a string with with Hex hasheCode
                         for (int i = 0; i < messageDigest.length; i++) {
                                 hexString.append(Integer.toHexString(0xFF & messageDigest[i]));
                         }
                 } catch (NoSuchAlgorithmException e) {
                         log.error(e);
                 }
                 return hexString.toString();
         }