Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.AddTestCommand.execute
execute
log
PARAM_NAME_TEST_DESCRIPTION
PARAM_NAME_TEST_TITLE
String by.epam.project.command.test.AddTestCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 18 of file AddTestCommand.java.
References by.epam.project.dao.DaoTest.addTest(), by.epam.project.resource.ConfigurationManager.getProperty(), and by.epam.project.dao.DaoTest.showTests().
{
                 String page = null;
                 String testTitle = request.getParameter(PARAM_NAME_TEST_TITLE).trim();
                 String testDescription = request.getParameter(
                                 PARAM_NAME_TEST_DESCRIPTION).trim();
                 // Checking for empty fields
                 DaoTest dao = new DaoTest();
                 if (testTitle.length() * testDescription.length() != 0) {
                         boolean result = dao.addTest(testTitle, testDescription);
                         if (result) {
                                 page = ConfigurationManager.getProperty("path.page.main_tutor");
                                 request.setAttribute("successfullyPerformedAction", "1");
                                 try {
                                         request.setAttribute("testsList", dao.showTests());
                                 } catch (TechnicalException e) {
                                         log.error(e);
                                 }
                         } else {
                                 page = ConfigurationManager.getProperty("path.page.main_tutor");
                                 request.setAttribute("successfullyPerformedAction", "0");
                         }
                 } else {
                         request.setAttribute("errorEmptyFieldMessage", "true");
                         try {
                                 request.setAttribute("testsList", dao.showTests());
                         } catch (TechnicalException e) {
                                 log.error(e);
                         }
                         page = ConfigurationManager.getProperty("path.page.main_tutor");
                 }
                 return page;
         }