Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.EditWriteAnswerCommand.execute
execute
log
PARAM_NAME_ANSWER_CONTENT
PARAM_NAME_ANSWER_ID
PARAM_NAME_ANSWER_VALUE
PARAM_NAME_QUESTION_ID
PARAM_TEST_ID
String by.epam.project.command.test.EditWriteAnswerCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 21 of file EditWriteAnswerCommand.java.
References by.epam.project.dao.DaoTest.editAnswer(), by.epam.project.resource.ConfigurationManager.getProperty(), and by.epam.project.dao.DaoTest.showQuestion().
{
                 String page = null;
                 String answerContent = request.getParameter(PARAM_NAME_ANSWER_CONTENT).trim();
                 int testId = Integer.parseInt(request.getParameter(PARAM_TEST_ID));
                 int answerId = Integer.parseInt(request.getParameter(
                                 PARAM_NAME_ANSWER_ID).trim());
                 int questionId = Integer.parseInt(request
                                 .getParameter(PARAM_NAME_QUESTION_ID));
                 int answerValue = Integer.parseInt(request.getParameter(
                                 PARAM_NAME_ANSWER_VALUE).trim());
                 // Checking for empty fields
                 DaoTest dao = new DaoTest();
                 if (answerContent.length() * answerId != 0) {
                         log.debug("parameters, received by command 'EditWriteAnswer' = "
                                         + answerId + " : " + answerValue + " : " + answerContent);
                         boolean result = dao.editAnswer(answerId, answerValue,
                                         answerContent);
                         if (result) {
                                 page = ConfigurationManager
                                                 .getProperty("path.page.edit_question");
                                 request.setAttribute("successfullyPerformedAction", "1");
                                 request.setAttribute("testId", testId);
                                 try {
                                         request.setAttribute("question",
                                                         dao.showQuestion(questionId));
                                 } catch (TechnicalException e) {
                                         log.error(e);
                                 }
                         } else {
                                 page = ConfigurationManager.getProperty("path.page.main_tutor");
                                 request.setAttribute("successfullyPerformedAction", "0");
                         }
                 } else {
                         request.setAttribute("errorEmptyFieldMessage", "true");
                         try {
                                 request.setAttribute("testId", testId);
                                 request.setAttribute("question", dao.showQuestion(questionId));
                         } catch (TechnicalException e) {
                                 log.error(e);
                         }
                         page = ConfigurationManager.getProperty("path.page.edit_question");
                 }
                 return page;
         }