Testing system (Written by Ivan Filimonau).: by.epam.project.pool.ConnectionPool.getSinglePool
cleanUpPool
ConnectionPool
createPool
getConnection
getSinglePool
instance
lock
log
pool
POOL_SIZE
returnConnection
static ConnectionPool by.epam.project.pool.ConnectionPool.getSinglePool () static
Definition at line 43 of file ConnectionPool.java.
References by.epam.project.pool.ConnectionPool.ConnectionPool(), by.epam.project.pool.ConnectionPool.instance, and by.epam.project.pool.ConnectionPool.lock.
Referenced by by.epam.project.dao.DaoTest.addAnswer(), by.epam.project.dao.DaoPerson.addPerson(), by.epam.project.dao.DaoTest.addQuestion(), by.epam.project.dao.DaoTest.addResult(), by.epam.project.dao.DaoTest.addTest(), by.epam.project.dao.DaoPerson.checkLogin(), by.epam.project.dao.DaoTest.deleteAnswer(), by.epam.project.dao.DaoPerson.deletePerson(), by.epam.project.dao.DaoTest.deleteQuestion(), by.epam.project.dao.DaoTest.deleteResult(), by.epam.project.dao.DaoTest.deleteTest(), by.epam.project.controller.Controller.destroy(), by.epam.project.dao.DaoTest.editAnswer(), by.epam.project.dao.DaoPerson.editPerson(), by.epam.project.dao.DaoTest.editQuestion(), by.epam.project.dao.DaoTest.editTest(), test.by.epam.project.TestConnectionPool.getConnectionTest(), by.epam.project.controller.Controller.init(), by.epam.project.dao.DaoPerson.showPerson(), by.epam.project.dao.DaoPerson.showPersons(), by.epam.project.dao.DaoTest.showQuestion(), by.epam.project.dao.DaoTest.showResult(), by.epam.project.dao.DaoPerson.showResults(), by.epam.project.dao.DaoTest.showTest(), and by.epam.project.dao.DaoTest.showTests().
{
                 if (instance == null) {
                         try {
                                 lock.lock();// gain blocking of the instance
                                 if (instance == null) {
                                         instance = new ConnectionPool();
                                 }
                         } finally {
                                 lock.unlock();// release blocking of the instance
                         }
                 }
                 return instance;
         }