Testing system (Written by Ivan Filimonau).: by.epam.project.logic.TestLogic.writeResult
calculateResult
checkQuestion
log
writeResult
boolean by.epam.project.logic.TestLogic.writeResult (int personId, int testId, int testMark)
Definition at line 86 of file TestLogic.java.
References by.epam.project.dao.DaoTest.addResult(), and by.epam.project.dao.DaoTest.deleteResult().
Referenced by by.epam.project.command.test.WriteResultCommand.execute().
{
                 DaoTest dao = new DaoTest();
                 try {
                         dao.addResult(personId, testId, testMark);
                 } catch (LogicException e) {
                         log.error(
                                         "From TestLogic.writeResult: pair 'personId===testType' already exist. Should be unique",
                                         e);
                         dao.deleteResult(personId, testId);
                         log.debug("From TestLogic.writeResult: existed pair 'personId===testType' successfully deleted");
                         try {
                                 dao.addResult(personId, testId, testMark);
                         } catch (LogicException e1) {
                                 log.error(e1);
                         }
                         log.debug("From TestLogic.writeResult: NEW pair 'personId===testType' successfully added");
                 }
                 return true;
         }