Testing system (Written by Ivan Filimonau).: by.epam.project.command.test.PerformTestCommand.execute
execute
log
PARAM_NAME_ID
PARAM_NAME_QUESTION_ID
PARAM_NAME_QUESTIONS_ID_LIST
PARAM_TEST_ID
String by.epam.project.command.test.PerformTestCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 27 of file PerformTestCommand.java.
References by.epam.project.resource.ConfigurationManager.getProperty(), by.epam.project.entity.test.Test.getQuestions(), by.epam.project.dao.DaoPerson.showPerson(), by.epam.project.dao.DaoTest.showQuestion(), and by.epam.project.dao.DaoTest.showTest().
{
                 String page = null;
                 Test test = null;
                 Question question = null;
                 int personId = Integer.parseInt(((String) request.getSession()
                                 .getAttribute(PARAM_NAME_ID)).trim());
                 int testId = Integer.parseInt(request.getParameter(PARAM_TEST_ID));
                 int questionId = 0;
                 // int questionId =
                 // Integer.parseInt(request.getParameter(PARAM_NAME_QUESTION_ID));
                 DaoTest dao = new DaoTest();
                 DaoPerson daoPerson = new DaoPerson();
                 TestLogic logic = new TestLogic();
                 Set<Question> questions = null;
                 ArrayList<Integer> questionsIdList = new ArrayList<>();
                 try {
                         if (request.getParameter(PARAM_NAME_QUESTION_ID) == null) {
                                 test = dao.showTest(testId);
                                 questions = test.getQuestions();
                                 for (Question elem : questions) {
                                         questionsIdList.add(elem.getId());
                                 }
                                 questionId = questionsIdList.get(0);
                         } else {
                                 questionId = Integer.parseInt(request
                                                 .getParameter(PARAM_NAME_QUESTION_ID));
                         }
                         // ----------------
                         page = ConfigurationManager.getProperty("path.page.perform_test");
                         request.setAttribute("test", test);
                         request.setAttribute("person", daoPerson.showPerson(personId));
                         request.setAttribute("question", dao.showQuestion(questionId));
                         request.setAttribute("questionsIdList", questionsIdList);
                 } catch (TechnicalException e) {
                         log.error(e);
                         page = ConfigurationManager.getProperty("path.page.login");
                 }catch (IndexOutOfBoundsException e){
                         log.error("---empty questions set for this test---", e);
                         page = ConfigurationManager.getProperty("path.page.login");
                 }
                 return page;
         }