Testing system (Written by Ivan Filimonau).: by.epam.project.dao.DaoPerson.showPersons
addPerson
checkLogin
deletePerson
editPerson
log
showPerson
showPerson
showPersons
showResults
SQL_ADD_PERSON
SQL_DELETE_PERSON_BY_ID
SQL_EDIT_PERSON
SQL_SELECT_USER_BY_LOGIN_AND_PASSWORD
SQL_SHOW_PERSON_BY_ID
SQL_SHOW_PERSONS
SQL_SHOW_RESULTS_BY_PERSON_ID
List<Person> by.epam.project.dao.DaoPerson.showPersons () throws TechnicalException
Definition at line 66 of file DaoPerson.java.
References by.epam.project.dao.Dao.closeStatement(), by.epam.project.pool.ConnectionPool.getConnection(), by.epam.project.pool.ConnectionPool.getSinglePool(), and by.epam.project.pool.ConnectionPool.returnConnection().
Referenced by by.epam.project.command.person.ShowPersonsCommand.execute().
{
                 List<Person> persons = new ArrayList<Person>();
                 Person person = null;
                 Connection cn = null;
                 Statement st = null;
                 try {
                         cn = ConnectionPool.getSinglePool().getConnection();
                         st = cn.createStatement();
                         ResultSet result = st.executeQuery(SQL_SHOW_PERSONS);
                         while (result.next()) {
                                 person = new Person();
                                 person.setId(result.getInt(1));
                                 person.setRoleType(result.getInt(2));
                                 person.setFirstName(result.getString(3));
                                 person.setSecondName(result.getString(4));
                                 person.setLogin(result.getString(5));
                                 person.setPassword(result.getString(6));
                                 persons.add(person);
                         }
                 } catch (SQLException e) {
                         throw new TechnicalException("DaoPerson.showPersons", e);
                 } finally {
                         Dao.closeStatement(st);
                         ConnectionPool.getSinglePool().returnConnection(cn);
                 }
                 return persons;
         }