Testing system. Written by Ivan Filimonau: by.epam.project.dao.DaoTest.addAnswer
addAnswer
addQuestion
addResult
addTest
deleteAnswer
deleteQuestion
deleteResult
deleteTest
editAnswer
editQuestion
editTest
log
showQuestion
showResult
showTest
showTests
SQL_ADD_ANSWER
SQL_ADD_QUESTION
SQL_ADD_RESULT
SQL_ADD_TEST
SQL_DELETE_ANSWER_BY_ID
SQL_DELETE_QUESTION_BY_ID
SQL_DELETE_RESULT_BY_PERSONID_TESTID
SQL_DELETE_TEST_BY_ID
SQL_EDIT_ANSWER
SQL_EDIT_QUESTION
SQL_EDIT_TEST
SQL_SHOW_ANSWERS_BY_QUESTION_TYPE
SQL_SHOW_QUESTION_BY_ID
SQL_SHOW_QUESTIONS_BY_TEST_TYPE
SQL_SHOW_RESULTS_BY_PERSON
SQL_SHOW_TEST_BY_ID
SQL_SHOW_TESTS_ID
boolean by.epam.project.dao.DaoTest.addAnswer (int questionId, String answerContent, int answerValue)
Definition at line 271 of file DaoTest.java.
References by.epam.project.dao.Dao.closeStatement(), by.epam.project.pool.ConnectionPool.getConnection(), by.epam.project.pool.ConnectionPool.getSinglePool(), and by.epam.project.pool.ConnectionPool.returnConnection().
Referenced by by.epam.project.command.test.AddAnswerCommand.execute().
{
                 Connection cn = null;
                 PreparedStatement st = null;
                 try {
                         cn = ConnectionPool.getSinglePool().getConnection();
                         st = cn.prepareStatement(SQL_ADD_ANSWER);
                         st.setInt(1, questionId);
                         st.setString(2, answerContent);
                         st.setInt(3, answerValue);
                         st.executeUpdate();
                 } catch (SQLException | TechnicalException e) {
                         log.error("Technical Exception", e);
                         return false;
                 } finally {
                         Dao.closeStatement(st);
                         ConnectionPool.getSinglePool().returnConnection(cn);
                 }
                 return true;
         }