Testing system. Written by Ivan Filimonau: by.epam.project.command.person.EditWritePersonCommand.execute
execute
log
PARAM_NAME_FIRST_NAME
PARAM_NAME_ID
PARAM_NAME_LOGIN
PARAM_NAME_PASSWORD
PARAM_NAME_ROLE
PARAM_NAME_SECOND_NAME
String by.epam.project.command.person.EditWritePersonCommand.execute (HttpServletRequest request)
Implements by.epam.project.command.ActionCommand.
Definition at line 24 of file EditWritePersonCommand.java.
References by.epam.project.dao.DaoPerson.editPerson(), by.epam.project.logic.LoginLogic.getHash(), and by.epam.project.resource.ConfigurationManager.getProperty().
{
                 String page = null;
                 // Extracting parameters from the request
                 String login = request.getParameter(PARAM_NAME_LOGIN);
                 String pass = request.getParameter(PARAM_NAME_PASSWORD);
                 String firstName = request.getParameter(PARAM_NAME_FIRST_NAME);
                 String secondName = request.getParameter(PARAM_NAME_SECOND_NAME);
                 int id = Integer.parseInt(request.getParameter(PARAM_NAME_ID).trim());
                 log.debug("String role = " + request.getParameter(PARAM_NAME_ROLE));
                 try {
                         int role = Integer.parseInt(request.getParameter(PARAM_NAME_ROLE)
                                         .trim());
                         log.debug("int role = " + role);
                         if (role < 1 && role > 3) {
                                 log.debug("Role does not equal 1,2 or 3");
                                 throw new LogicException("Role does not equal 1,2 or 3");
                         }
                         if (firstName.length() * secondName.length() * login.length()
                                         * pass.length() == 0) {
                                 request.setAttribute("errorEmptyFieldMessage", "true");
                                 page = ConfigurationManager.getProperty("path.page.edit_user");
                         } else {
                                 DaoPerson dao = new DaoPerson();
                                 LoginLogic logic = new LoginLogic();
                                 String passMd5 = logic.getHash(pass);
                                 boolean result = dao.editPerson(id, role, firstName,
                                                 secondName, login, passMd5);
                                 // Return string with the address of the login page
                                 if (result) {
                                         page = ConfigurationManager
                                                         .getProperty("path.page.main_root");
                                         request.setAttribute("successfullyPerformedAction", "1");
                                 }else{
                                         page = ConfigurationManager
                                                         .getProperty("path.page.main_root");
                                         request.setAttribute("successfullyPerformedAction", "0");
                                 }
                                 log.debug("command editWrite performed. Result = " + result);
                                 log.debug(request.getAttribute("successfullyPerformedAction"));
                         }
                 } catch (NumberFormatException | LogicException e) {
                         log.error(e);
                         request.setAttribute("errorNonNumberMessage", "true");
                         page = ConfigurationManager.getProperty("path.page.edit_user");
                 }
                 return page;
         }